---
title: "Insomnia pairwise MAs"
subtitle: "Prepared by Virginia Chiocchia on 30th July, refers to a single outcome analysis (Total Sleep Time) in a frequentist setting"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 3)
```

```{r, include=FALSE}
library(devtools)
install_github("esm-ispm-unibe-ch/NMAJags")
library(NMAJags)
library(R2jags)
library(netmeta)
library(meta)
library(metafor)
library(readxl)
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}
#get the data and select them
DATA <- read_excel("~/Virginia/NMA insomnia/Insomnia/MyrtoIncludedAllOutcomesClean27.6dVirgiRenamedInterventions.xlsx", na = "NA")


```



```{r, include=FALSE}
#prepare the data
DATApairs=pairwise(treat=Drug_name,mean=SleepTimeTotalScaleMean,sd=SleepTimeTotalScaleSD,n=SleepTimeTotalScaleParticipants, data=DATA, studlab = Final_ID_all)

netconnection(treat1,treat2,studlab,data=DATApairs,warn = T)

#check p-value availability for paired t-test for crossover studies with both phases used
DATApairs[DATApairs$Crossoverstudy==1 & DATApairs$`crossover, not first phase used`==1,c("studlab","tst_PorF-value","tst_p=0, f=1")]
# use threshold value for those with p-value <0.001
DATApairs[DATApairs$studlab==185, "tst_PorF-value"] <- 0.00099
#now calculate adjusted SE for remaining crossover studies
DATApairs$tvalue <- qt(as.numeric(DATApairs$`tst_PorF-value`)/2, df=DATApairs$n1-1, lower.tail = F)
DATApairs$SDd <- abs((DATApairs$mean2-DATApairs$mean1)/DATApairs$tvalue*sqrt(DATApairs$n1))
DATApairs$rho <- (DATApairs$sd1^2 + DATApairs$sd2^2 - DATApairs$SDd^2)/(2*DATApairs$sd1*DATApairs$sd2)
DATApairs[DATApairs$Crossoverstudy==1 & DATApairs$`crossover, not first phase used`==1,"seTE"] <- sqrt((1/DATApairs$n1+(DATApairs$TE^2)/(2*DATApairs$n1))*(2-2*DATApairs$rho))[DATApairs$Crossoverstudy==1 & DATApairs$`crossover, not first phase used`==1] 

```

```{r, echo=FALSE}
# acetaminophen vs placebo
TSTma1 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="acetaminophen", label.e = DATApairs$treat1[1], label.c = DATApairs$treat2[1])

#forest plots
forest(TSTma1, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
# artifical vs tart cherry juice
TSTma2 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="artificial juice", label.e = "artificial juice", label.c = "tart cherry juice")

#forest plots
forest(TSTma2, digits=1, digits.sd = 1)
```

```{r, echo=FALSE}
# BBT I vs self-monitoring control
TSTma3 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="BBT I", label.e = "BBT I", label.c = "self-monitoring control")

#forest plots
forest(TSTma3, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
# chlormethiazole vs temazepam
TSTma4 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="chlormethiazole", label.e = "chlormethiazole", label.c = "temazepam")

#forest plots
forest(TSTma4, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
# diazepam vs pbo
TSTma5 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="diazepam" &  DATApairs$treat2=="pbo", label.e = "diazepam", label.c = "pbo")

#forest plots
forest(TSTma5, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
# diazepam vs promethazine
TSTma6 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="diazepam" &  DATApairs$treat2=="promethazine", label.e = "diazepam", label.c = "promethazine")

#forest plots
forest(TSTma6, digits=1, digits.sd = 1)
```

```{r, echo=FALSE}
# diazepam vs propiomazine
TSTma7 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="diazepam" &  DATApairs$treat2=="propiomazine", label.e = "diazepam" , label.c = "propiomazine")

#forest plots
forest(TSTma7, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
# diphenhydramine vs pbo
TSTma8 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="diphenhydramine" &  DATApairs$treat2=="pbo", label.e = "diphenhydramine", label.c = "pbo")

#forest plots
forest(TSTma8, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
# diphenhydramine vs temazepam
TSTma9 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="diphenhydramine" &  DATApairs$treat2=="temazepam", label.e = "diphenhydramine", label.c = "temazepam")

#forest plots
forest(TSTma9, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE, fig.width = 10, fig.height = 3}
# doxepin vs pbo
TSTma10 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="doxepin", label.e = "doxepin", label.c = "pbo")

#forest plots
forest(TSTma10, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
# esmirtazapine vs pbo
TSTma11 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="esmirtazapine", label.e = "esmirtazapine", label.c = "pbo")

#forest plots
forest(TSTma11, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE, fig.width = 10, fig.height = 3}
# eszopiclone vs pbo
TSTma12 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="eszopiclone", label.e = "eszopiclone", label.c = "pbo")

#forest plots
forest(TSTma12, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
# flunitrazepam vs nitrazepam
TSTma13 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="flunitrazepam", label.e = DATApairs$treat1[16], label.c = DATApairs$treat2[16])

#forest plots
forest(TSTma13, digits=1, digits.sd = 1)
```

The study above was in psychogeriatric patients and therefore not included in main NMA.


```{r, echo=FALSE}
# food supplement vs pbo
TSTma14 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = grep("food supplement", DATApairs$treat1), label.e = "food supplement", label.c = "pbo")

#forest plots
forest(TSTma14, digits=1, digits.sd = 1, just = "center")
```
```{r, echo=FALSE}
# LAT vs MAT
TSTma15 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="LAT" &  DATApairs$treat2=="MAT", label.e = "LAT", label.c = "MAT")

#forest plots
forest(TSTma15, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
# LAT vs MAT+LAT
TSTma16 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="LAT" &  DATApairs$treat2=="MAT+LAT", label.e = "LAT", label.c = "MAT+LAT")

#forest plots
forest(TSTma16, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
# MAT vs MAT+LAT
TSTma17 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="MAT" &  DATApairs$treat2=="MAT+LAT", label.e = "MAT", label.c = "MAT+LAT")

#forest plots
forest(TSTma17, digits=1, digits.sd = 1, just = "center")
```
```{r, echo=FALSE}
# loprazolam vs nitrazepam
TSTma18 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="loprazolam" &  DATApairs$treat2=="nitrazepam", label.e = "loprazolam", label.c = "nitrazepam")

#forest plots
forest(TSTma18, digits=1, digits.sd = 1)
```

```{r, echo=FALSE}
# loprazolam vs pbo
TSTma19 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="loprazolam" &  DATApairs$treat2=="pbo", label.e = "loprazolam", label.c = "pbo")

#forest plots
forest(TSTma19, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
# loprazolam+sleep hygiene vs sleep hygiene
TSTma20 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat2=="sleep hygiene", label.e = "loprazolam + sleep hygiene", label.c = "sleep hygiene")

#forest plots
forest(TSTma20, digits=1, digits.sd = 1)
```

```{r, echo=FALSE}
#  melatonin vs pbo
TSTma21 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="melatonin", label.e = "melatonin", label.c = "pbo")

#forest plots
forest(TSTma21, digits=1, digits.sd = 1, just = "center")
```
```{r, echo=FALSE}
#  midazolam vs oxazepam
TSTma22 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="midazolam", label.e = "midazolam", label.c = "oxazepam")

#forest plots
forest(TSTma22, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
#  pbo vs temazepam
TSTma23 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="pbo" & DATApairs$treat2=="temazepam", label.e = "pbo", label.c = "temazepam")

#forest plots
forest(TSTma23, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
#  pbo vs ramelteon
TSTma24 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="pbo" & DATApairs$treat2=="ramelteon", label.e = "pbo", label.c = "ramelteon")

#forest plots
forest(TSTma24, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
#  pbo vs promethazine
TSTma25 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="pbo" & DATApairs$treat2=="promethazine", label.e = "pbo", label.c = "promethazine")

#forest plots
forest(TSTma25, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
#  pbo vs propiomazine
TSTma26 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="pbo" & DATApairs$treat2=="propiomazine", label.e = "pbo", label.c = "propiomazine")

#forest plots
forest(TSTma26, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
#  pbo vs zolpidem
TSTma27 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="pbo" & DATApairs$treat2=="zolpidem", label.e = "pbo", label.c = "zolpidem")

#forest plots
forest(TSTma27, digits=1, digits.sd = 1, just = "center")
```

```{r, echo=FALSE}
#  promethazine vs propiomazine
TSTma28 <- metacont(n1,mean1,sd1,n2,mean2,sd2, studlab=DATApairs$Study_name, data=DATApairs, subset = DATApairs$treat1=="promethazine" & DATApairs$treat2=="propiomazine", label.e = "promethazine", label.c = "propiomazine")

#forest plots
forest(TSTma28, digits=1, digits.sd = 1, just = "center")
```
